{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-template.fullname" . }}-prometheus-config
  labels:
    {{- include "go-template.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "otel-collector"
        static_configs:
          - targets: ["{{ include "go-template.fullname" . }}-otel-collector:8889"]
{{- end }}