{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-template.fullname" . }}-prometheus
  labels:
    {{- include "go-template.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-template.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "go-template.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "go-template.fullname" . }}-prometheus-config
{{- end }}