{{- if .Values.goTemplate.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-template.fullname" . }}-config
  labels:
    {{- include "go-template.labels" . | nindent 4 }}
    app.kubernetes.io/component: go-template
data:
  {{- range $key, $val := .Values.goTemplate.env }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
