apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-template.fullname" . }}-config
  labels:
    {{- include "go-template.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.goTemplate.config.logLevel }}
  SERVER_PORT: {{ .Values.goTemplate.config.serverPort | quote }}