receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  debug: # Required for traces/logs (or use another exporter like otlphttp)

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # Or your trace backend (e.g., otlphttp, jaeger)
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # Or your log backend (e.g., loki, elasticsearch)
