apiVersion: v1
kind: Service
metadata:
  name: go-template
  labels:
    app.kubernetes.io/name: go-template
  annotations:
    networking.gke.io/load-balancer-type: Internal
spec:
  selector:
    app.kubernetes.io/name: go-template
  ports:
    - name: http-api
      port: 80
      targetPort: http-api
  type: LoadBalancer
