goTemplate:
  enabled: true
  image:
    repository: go-template
    tag: latest
    pullPolicy: Always

  replicaCount: 1

  service:
    type: LoadBalancer
    port: 80
    annotations:
      networking.gke.io/load-balancer-type: Internal

  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

  env:
    LOG_LEVEL: info
    SERVER_PORT: "80"
    OTEL_HOST: 10.2.34.227

  nodePool: ""

otelCollector:
  enabled: true
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.127.0
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 4317

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  nodePool: ""

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v3.4.1
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 9090

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  nodePool: ""

loki:
  enabled: true
  image:
    repository: grafana/loki
    tag: 3.3.0
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 3100

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""

  nodePool: ""

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: 12.0.1
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 3000

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""

  adminUser: admin
  adminPassword: admin

  nodePool: ""
