api_keys: 
  - 6f15e730-0eb6-11e3-9053-af0e97bcb74e
enable_docs: true
enable_pprof: true
server:
  mode: debug
  host: 0.0.0.0
  port: 80
  shutdown_timeout: 10
log:
  level: debug
  encoding: json # json or console
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]
  show_file_line: true
  encoder_config:
    message_key: message
    level_key: level
    level_encoder: lowercase
    time_key: timestamp
    time_encoder: iso8601
database:
  name: postgres
  username: postgres
  postgres: postgres
  host: host.docker.internal
  port: 5432
